Algoritmo "Verificação de Intervalo"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 05/03/2026
Var
// Seção de Declarações das variáveis 
numero: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um numero: ")
leia(numero)
 se (numero >= 10) e (numero <= 50) entao
     escreva("O número ", numero, " está entre 10 e 50.")
senao
     escreva("O número ", numero, " NÃO está entre 10 e 50.")
fimse
Fimalgoritmo